{% set python_min = "3.11" %}
{% set name = "pontibus" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/pontibus/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 787d95f0086074d842440cad6e8da3c830ab434427a1837e379e42f2c49cbce6

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - gufe >=1.7
    - openfe >=1.8
    - numpy <2.3
    - openmm !=8.1.0,>=8.0.0,<8.3.0
    - openmmtools >0.24
    - openff-interchange >=0.4.8,<0.5
    - openff-nagl-base >=0.3.3
    - pydantic >=2.0
    - python >={{ python_min }}
    - rdkit !=2024.03.06

test:
  imports:
    - pontibus
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -c "import pontibus; assert(pontibus.__version__ == '0.4.0')"
    - pytest -v --pyargs pontibus

about:
  home: https://github.com/OpenFreeEnergy/pontibus
  summary: 'pontibus: experimental FF validation Protocols'
  description: |
    Experimental OpenFE Protocols for Force Field Evaluation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pontibus.readthedocs.io/
  dev_url: https://github.com/OpenFreeEnergy/pontibus

extra:
  recipe-maintainers:
    - IAlibay
